### ISSUE TITLE
Accessing a protected page redirects to CKAN login page rather than CAS login page

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ckanext-georchestra#1]
eg /ckan/harvest/pigma/job/f91b5115-e16d-4455-9047-1fd9922e4f82 redirects to /user/login?came_from=http%3A%2F%2Ffqdn%2Fharvest%2Fpigma%2Fjob%2Ff91b5115-e16d-4455-9047-1fd9922e4f82

Expected :  /ckan/harvest/pigma/job/f91b5115-e16d-4455-9047-1fd9922e4f82 redirects to /ckan/harvest/pigma/job/f91b5115-e16d-4455-9047-1fd9922e4f82?login which will be interpreted by the SP.

**Comment by jeanpommier** [comment]
fixed by https://github.com/georchestra/ckanext-georchestra/pull/11
