### ISSUE TITLE
"profile updated" 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ckanext-georchestra#2]
/ckan/dashboard/ shows
![Capture du 2019-03-11 13-51-57](https://user-images.githubusercontent.com/265319/54125289-e55ac580-4404-11e9-9b39-514ea9b74126.png)

But I'm pretty sure @jeanpommier 's work on LDAP sync will solve this issue.

**Comment by jeanpommier** [comment]
Yes, @fvanderbiest , it should by comparing update times on both LDAP and CKAN

**Comment by jeanpommier** [comment]
Current version fixes it, indeed
