### ISSUE TITLE
Missing CKAN_LDAP_URL

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ckanext-georchestra#5]
CKAN currently has the ability to configure itself through ENV vars.
This is very convenient. See https://docs.ckan.org/en/ckan-2.7.3/maintaining/configuration.html#environment-variables

What is now missing with this extension is the ability to get CKAN_LDAP_URL from an env var.

**Comment by jeanpommier** [comment]
Fixed by https://github.com/georchestra/ckanext-georchestra/pull/12
